// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportReason } from "./ReportReason";

/**
 * 通報リクエスト
 */
export type ReportRequest = { target_user_id: string, reason: ReportReason, detail: string | null, };
