// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 通報理由の選択肢
 */
// export type ReportReason = "inappropriate_language" | "spam" | "harassment" | "other";
export const REPORT_REASON = [
    "inappropriate_language", "spam", "harassment", "other"
] as const;
export type ReportReason = typeof REPORT_REASON[number];