// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 通報理由の選択肢
 */
export type ReportReason = "inappropriate_language" | "spam" | "harassment" | "other";
