// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * システムイベントの種類
 */
export type SystemEvent = { "type": "partner_disconnected" } | { "type": "matching_completed" };
