name: Frontend Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      # Node.jsのセットアップとpnpmのキャッシュ設定
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml 

      # 依存関係のインストール
      - name: Install dependencies
        run: pnpm install

      # pnpm checkの実行
      - name: Run pnpm check
        run: pnpm run check

      - name: Run build
        run: pnpm build